packages:
  - "apps/desktop"
  - "packages/*"

overrides:
  "@xmldom/xmldom@<0.8.13": "0.8.13"
  "brace-expansion@<1.1.18": "1.1.18"
  "brace-expansion@>=2.0.0 <2.1.4": "2.1.4"
  "brace-expansion@>=5.0.0 <5.0.9": "5.0.9"
  "esbuild@>=0.27.3 <0.28.1": "0.28.2"
  "form-data@<4.0.6": "4.0.6"
  js-yaml: "4.3.1"
  "tar@<7.5.22": "7.5.22"
  "tmp@<0.2.7": "0.2.7"

onlyBuiltDependencies:
  - "@swc/core"
  - electron
  - electron-winstaller
  - esbuild
  - ffmpeg-static
  - uiohook-napi

allowBuilds:
  '@swc/core': set this to true or false
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
  ffmpeg-static: set this to true or false
