export const IPC_CHANNELS = {
  app: {
    getRuntimeInfo: "app:get-runtime-info",
    getSystemIdleSeconds: "app:get-system-idle-seconds",
    writeLog: "app:write-log",
    notify: "app:notify",
    readChatHistory: "app:read-chat-history",
    saveChatHistory: "app:save-chat-history",
    openExternal: "app:open-external",
    getLinkPreviewIcon: "app:get-link-preview-icon",
    consumeDeepLink: "app:consume-deep-link",
    deepLink: "app:deep-link",
  },
  clipboard: {
    writeText: "clipboard:write-text",
    writeImage: "clipboard:write-image",
  },
  audio: {
    getDeepFilterAssets: "audio:get-deepfilter-assets",
  },
  screenCapture: {
    listSources: "screen-capture:list-sources",
    selectSource: "screen-capture:select-source",
    setContentProtection: "screen-capture:set-content-protection",
  },
  screenShareViewer: {
    open: "screen-share-viewer:open",
    sendSignal: "screen-share-viewer:send-signal",
    close: "screen-share-viewer:close",
    signal: "screen-share-viewer:signal",
  },
  window: {
    minimize: "window:minimize",
    toggleMaximize: "window:toggle-maximize",
    hide: "window:hide",
    close: "window:close",
    show: "window:show",
  },
  overlay: {
    show: "overlay:show",
    toggle: "overlay:toggle",
    close: "overlay:close",
    update: "overlay:update",
    state: "overlay:state",
  },
  games: {
    getSnapshot: "games:get-snapshot",
    detected: "games:detected",
  },
  settings: {
    get: "settings:get",
    save: "settings:save",
    reset: "settings:reset",
  },
  profile: {
    pickAvatar: "profile:pick-avatar",
    readAvatar: "profile:read-avatar",
    clearAvatar: "profile:clear-avatar",
  },
  diagnostics: {
    snapshot: "diagnostics:snapshot",
    testServer: "diagnostics:test-server",
    exportLogs: "diagnostics:export-logs",
    exportBundle: "diagnostics:export-bundle",
    openLogsDirectory: "diagnostics:open-logs-directory",
  },
  windows: {
    getStatus: "windows:get-status",
    repairFirewall: "windows:repair-firewall",
    removeFirewall: "windows:remove-firewall",
  },
  shortcuts: {
    configureMute: "shortcuts:configure-mute",
    muteTriggered: "shortcuts:mute-triggered",
    configureRecordingMarker: "shortcuts:configure-recording-marker",
    recordingMarkerTriggered: "shortcuts:recording-marker-triggered",
  },
  updates: {
    check: "updates:check",
    download: "updates:download",
    install: "updates:install",
    status: "updates:status",
    openReleases: "updates:open-releases",
  },
  signaling: {
    connect: "signaling:connect",
    send: "signaling:send",
    close: "signaling:close",
    event: "signaling:event",
  },
  recording: {
    export: "recording:export",
    chooseDirectory: "recording:choose-directory",
    saveMarkers: "recording:save-markers",
    list: "recording:list",
    openDirectory: "recording:open-directory",
    delete: "recording:delete",
  },
} as const;
