export const IPC_CHANNELS = {
  app: {
    getRuntimeInfo: "app:get-runtime-info",
    getSystemIdleSeconds: "app:get-system-idle-seconds",
    writeLog: "app:write-log",
    notify: "app:notify",
    readChatHistory: "app:read-chat-history",
    saveChatHistory: "app:save-chat-history",
    readDailyRoomReports: "app:read-daily-room-reports",
    saveDailyRoomReports: "app:save-daily-room-reports",
    openExternal: "app:open-external",
    openSystemSettings: "app:open-system-settings",
    getLinkPreviewIcon: "app:get-link-preview-icon",
    consumeDeepLink: "app:consume-deep-link",
    deepLink: "app:deep-link",
    lifecycleRecovery: "app:lifecycle-recovery",
  },
  clipboard: {
    writeText: "clipboard:write-text",
    writeImage: "clipboard:write-image",
  },
  audio: {
    getDeepFilterAssets: "audio:get-deepfilter-assets",
  },
  quickMessages: {
    export: "quick-messages:export",
  },
  screenCapture: {
    listSources: "screen-capture:list-sources",
    selectSource: "screen-capture:select-source",
    setContentProtection: "screen-capture:set-content-protection",
  },
  screenShareViewer: {
    open: "screen-share-viewer:open",
    sendSignal: "screen-share-viewer:send-signal",
    close: "screen-share-viewer:close",
    signal: "screen-share-viewer:signal",
  },
  window: {
    minimize: "window:minimize",
    toggleMaximize: "window:toggle-maximize",
    hide: "window:hide",
    close: "window:close",
    show: "window:show",
  },
  overlay: {
    show: "overlay:show",
    toggle: "overlay:toggle",
    close: "overlay:close",
    update: "overlay:update",
    setInteractive: "overlay:set-interactive",
    moveTo: "overlay:move-to",
    resetPosition: "overlay:reset-position",
    requestMuteQuickMessage: "overlay:request-mute-quick-message",
    muteQuickMessage: "overlay:mute-quick-message",
    state: "overlay:state",
    hoverState: "overlay:hover-state",
  },
  games: {
    getSnapshot: "games:get-snapshot",
    detected: "games:detected",
  },
  weather: {
    getSnapshot: "weather:get-snapshot",
  },
  ai: {
    getSnapshot: "ai:get-snapshot",
    controlModel: "ai:control-model",
    status: "ai:status",
    runtimeStatus: "ai:runtime-status",
    getVoiceMemory: "ai:get-voice-memory",
    listVoiceMemories: "ai:list-voice-memories",
    processRecording: "ai:process-recording",
    selectTranscription: "ai:select-transcription",
    pauseTask: "ai:pause-task",
    resumeTask: "ai:resume-task",
    assignSpeaker: "ai:assign-speaker",
    updateMarkerTitle: "ai:update-marker-title",
    askRecording: "ai:ask-recording",
    askMemory: "ai:ask-memory",
    cancelQuestion: "ai:cancel-question",
    searchMemory: "ai:search-memory",
    getCustomProvider: "ai:get-custom-provider",
    saveCustomProvider: "ai:save-custom-provider",
    clearCustomProvider: "ai:clear-custom-provider",
    getHuggingFaceAccess: "ai:get-hugging-face-access",
    saveHuggingFaceAccess: "ai:save-hugging-face-access",
    clearHuggingFaceAccess: "ai:clear-hugging-face-access",
    updateRuntimePressure: "ai:update-runtime-pressure",
    voiceMemoryStatus: "ai:voice-memory-status",
  },
  settings: {
    get: "settings:get",
    save: "settings:save",
    reset: "settings:reset",
  },
  account: {
    getSnapshot: "account:get-snapshot",
    configureCloudBase: "account:configure-cloudbase",
    login: "account:login",
    register: "account:register",
    requestVerificationCode: "account:request-verification-code",
    requestPasswordReset: "account:request-password-reset",
    updateProfile: "account:update-profile",
    updateAvatar: "account:update-avatar",
    logout: "account:logout",
    continueAsGuest: "account:continue-as-guest",
    changed: "account:changed",
  },
  profile: {
    pickAvatar: "profile:pick-avatar",
    readAvatar: "profile:read-avatar",
    clearAvatar: "profile:clear-avatar",
  },
  diagnostics: {
    snapshot: "diagnostics:snapshot",
    runtimeHealth: "diagnostics:runtime-health",
    testServer: "diagnostics:test-server",
    exportLogs: "diagnostics:export-logs",
    exportBundle: "diagnostics:export-bundle",
    openLogsDirectory: "diagnostics:open-logs-directory",
  },
  windows: {
    getStatus: "windows:get-status",
    repairFirewall: "windows:repair-firewall",
    removeFirewall: "windows:remove-firewall",
    setIconOverlaysHidden: "windows:set-icon-overlays-hidden",
  },
  shortcuts: {
    configureMute: "shortcuts:configure-mute",
    muteTriggered: "shortcuts:mute-triggered",
    configureRecordingMarker: "shortcuts:configure-recording-marker",
    recordingMarkerTriggered: "shortcuts:recording-marker-triggered",
    configurePushToTalk: "shortcuts:configure-push-to-talk",
    pushToTalkState: "shortcuts:push-to-talk-state",
    configureQuickMessage: "shortcuts:configure-quick-message",
    quickMessageTriggered: "shortcuts:quick-message-triggered",
  },
  updates: {
    check: "updates:check",
    download: "updates:download",
    install: "updates:install",
    status: "updates:status",
    openReleases: "updates:open-releases",
  },
  signaling: {
    connect: "signaling:connect",
    send: "signaling:send",
    close: "signaling:close",
    injectFault: "signaling:inject-fault",
    event: "signaling:event",
  },
  recording: {
    export: "recording:export",
    saveSpeakerSegment: "recording:save-speaker-segment",
    finalizeSpeakerSegments: "recording:finalize-speaker-segments",
    saveParticipantTrack: "recording:save-participant-track",
    finalizeParticipantTracks: "recording:finalize-participant-tracks",
    chooseDirectory: "recording:choose-directory",
    saveMarkers: "recording:save-markers",
    applyAutomaticCleanup: "recording:apply-automatic-cleanup",
    list: "recording:list",
    scanWaste: "recording:scan-waste",
    scanWasteProgress: "recording:scan-waste-progress",
    setFavorite: "recording:set-favorite",
    rename: "recording:rename",
    openDirectory: "recording:open-directory",
    showItemInFolder: "recording:show-item-in-folder",
    delete: "recording:delete",
    deleteMany: "recording:delete-many",
  },
} as const;
