server {
    listen 80;
    server_name 118.25.103.107;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/shanghao-acme;
        default_type text/plain;
        try_files $uri =404;
    }

    location / { return 404; }
}
