export const PHONE_MIC_USB_PAGE = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>上号 · 手机麦克风</title>
<style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:linear-gradient(150deg,#dcecff,#f8fbff);font:16px system-ui,sans-serif;color:#294264}main{width:min(360px,calc(100% - 48px));padding:28px;border:1px solid #fff;border-radius:28px;background:#ffffffbb;box-shadow:0 24px 60px #4a78aa29;backdrop-filter:blur(20px)}h1{font-size:23px;margin:0 0 8px}p{line-height:1.5;color:#627a98}button{width:100%;border:0;border-radius:14px;padding:14px;color:#fff;background:#468fe6;font:600 17px system-ui}button:disabled{opacity:.5}#meter{height:10px;background:#dce8f8;border-radius:10px;overflow:hidden;margin:20px 0}#bar{height:100%;width:0;background:#55ba9c;transition:width .1s}small{display:block;margin-top:14px;color:#657c98}</style></head>
<body><main><h1>上号 · 手机麦克风</h1><p id="status">USB 已连接，等待麦克风授权。</p><div id="meter"><div id="bar"></div></div><button id="toggle">开始传输</button><small>请保持此页面打开；停止后麦克风权限会释放。</small></main>
<script>
const statusEl=document.getElementById('status'),toggle=document.getElementById('toggle'),bar=document.getElementById('bar');
const code=new URLSearchParams(location.hash.slice(1)).get('code');let stream,context,source,node,socket,active=false;
const processor=\`class Capture extends AudioWorkletProcessor{constructor(){super();this.samples=new Float32Array(480);this.offset=0}process(inputs){const channels=inputs[0];if(!channels?.[0])return true;const input=channels[0];for(let i=0;i<input.length;i++){this.samples[this.offset++]=input[i];if(this.offset===480){const frame=this.samples;this.samples=new Float32Array(480);this.offset=0;this.port.postMessage(frame,[frame.buffer])}}return true}}registerProcessor('shanghao-usb-capture',Capture);\`;
async function stop(){active=false;toggle.textContent='开始传输';try{socket?.close()}catch{}socket=undefined;try{source?.disconnect();node?.disconnect()}catch{}source=undefined;node=undefined;await context?.close().catch(()=>{});context=undefined;stream?.getTracks().forEach(t=>t.stop());stream=undefined;bar.style.width='0';statusEl.textContent='已停止传输。'}
async function start(){if(!code){statusEl.textContent='配对信息无效，请重新扫码。';return}toggle.disabled=true;try{stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:false,noiseSuppression:false,autoGainControl:false}});context=new AudioContext({sampleRate:48000});await context.resume();if(context.sampleRate!==48000)throw Error('当前浏览器无法提供 48 kHz 音频');const url=URL.createObjectURL(new Blob([processor],{type:'text/javascript'}));try{await context.audioWorklet.addModule(url)}finally{URL.revokeObjectURL(url)}socket=new WebSocket('ws://'+location.host+'/usb/ws?role=sender&code='+encodeURIComponent(code));socket.binaryType='arraybuffer';await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=()=>reject(Error('USB 连接失败'))});source=context.createMediaStreamSource(stream);node=new AudioWorkletNode(context,'shanghao-usb-capture');source.connect(node);node.connect(context.destination);let sequence=0,lastMeterAt=0;node.port.onmessage=event=>{if(socket?.readyState!==WebSocket.OPEN||socket.bufferedAmount>64000)return;const samples=event.data;const frame=new ArrayBuffer(8+samples.byteLength);const view=new DataView(frame);view.setUint32(0,sequence++,true);view.setUint32(4,Date.now()>>>0,true);new Float32Array(frame,8).set(samples);socket.send(frame);if(performance.now()-lastMeterAt<50)return;lastMeterAt=performance.now();let peak=0;for(let i=0;i<samples.length;i++)peak=Math.max(peak,Math.abs(samples[i]));bar.style.width=Math.min(100,peak*140)+'%'};socket.onclose=()=>{if(active)void stop()};active=true;toggle.textContent='停止传输';statusEl.textContent='正在通过 USB 传输 · '+stream.getAudioTracks()[0].label;}catch(error){await stop();statusEl.textContent=error?.message||'麦克风连接失败'}finally{toggle.disabled=false}}
toggle.onclick=()=>active?void stop():void start();window.addEventListener('pagehide',()=>void stop());
</script></body></html>`;
